spring.application.name=web_adventure

## Database Configuration for Phuc
#spring.datasource.url=jdbc:postgresql://localhost:5432/web_adventure
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver

## Database Configuration for Viet
#spring.datasource.url=jdbc:postgresql://localhost:15555/web_adventure
#spring.datasource.username=postgres
#spring.datasource.password=19072004
#spring.datasource.driver-class-name=org.postgresql.Driver

# Database Configuration for Phuong senior


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=12345
